### ISSUE TITLE
silenceMessage isn't throwing on some errors

### ISSUE THREAD

**Issue by notthatnathan** [ricardo-ch/jest-fail-on-console#3] opened 2021-05-03 20:45 UTC
```js
  silenceMessage: (errorMessage, methodName) => {
    if (/test was not wrapped in act/.test(errorMessage)) {
      return true;
    }

    if (
      /It looks like you're using a version of react-dom that supports the "act" function/.test(
        errorMessage,
      )
    ) {
      return true;
    }

    console.log('errorMessage', methodName, errorMessage);
    return false;
  },
```

```
    errorMessage error Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

```
Test Suites: 1 passed, 1 total
Tests:       18 passed, 18 total
```

This successfully silences the errors I'm excepting by returning `true`. But it's not throwing on the other `console.error` instances in the same component.

**Comment by notthatnathan** [comment] 2021-05-03 21:01
I just realized this is probably because the message passed to `console.error` in those cases wasn't an instance of `Error`. 

So I guess this is a request to update this to work with strings not just `Error`'s.

**Comment by ValentinH** [comment] 2021-06-29 08:06
Sorry for answering so late (I wasn't watching this repo 🙈). I'm not sure to understand what the issue is. Could you share an example?

**Comment by notthatnathan** [comment] 2021-06-29 13:30
In my example above, the React error "Can't perform a React state update on an unmounted component" does not trigger a test failure, even though I'm the log confirms it's hitting `silenceMessage` and returning `false`.

**Comment by ValentinH** [comment] 2021-06-29 13:55
This is weird. Do you have the same behaviour if you remove your custom `silenceMessage` function?

**Comment by notthatnathan** [comment] 2021-06-29 14:04
I'm sorry, I'd moved on to a custom solution, so I don't have that in front of me. My recollection is the tests still passed with those React "warnings" that are actually `console.error` logs. Don't hold me to it.

**Comment by ValentinH** [comment] 2021-07-12 09:36
Ok, I'm closing this then. Please comment if you are able to reproduce the issue so we can re-open it. 🙂

**Closed by ValentinH** 2021-07-12 09:36 UTC
